🐛 Require bootstrap externalUrl param (#161)
- This is used for the redirect-uri for the generated users
- as such, it must be set when we initialize the users, or they won't be able to log in to abacus
- Really, this should probably be a list? So we can have both abacus and other services running on different domains or maybe be more explicit about specific redirect paths

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -43,11 +43,18 @@ jobs:
       - name: Render Templates
         run: |
           cd charts
-          for d in */ ; do
-              if [ -f "$d/Chart.yaml" ]; then
-                echo "Rendering Helm chart $d to validate defaults..."
-                helm template "$d"
+          for d in * ; do
+            if [[ $d == keycloak_bootstrap ]]; then
+              echo "Rendering Helm chart to validate defaults..."
+              helm template --set externalUrl=http://nowhere "$d"
+              if helm template "$d"; then
+                echo "$d should fail with defaults, as it has a required parameter"
+                exit 1
               fi
+            elif [ -f "$d/Chart.yaml" ]; then
+              echo "Rendering Helm chart $d to validate defaults..."
+              helm template "$d"
+            fi
           done
 
   scriptcheck:
