move to release workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -10,8 +10,39 @@ on:
 # This workflow assumes the release tag is the literal Semver you want to use to stamp the release charts with.
 # This workflow will bake images into the (human-readable SEMVER from tag) charts using (generated from current tag SHA) tagged image builds, which presumably have already been built+pushed for this SHA
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Get branch name (not PR)
+        if: github.event_name != 'pull_request'
+        shell: bash
+        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
+
+      - name: Get branch name (PR)
+        if: github.event_name == 'pull_request'
+        shell: bash
+        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
+
+      - name: Debug
+        run: echo ${{ env.BRANCH_NAME }}
+
+      - name: Check branch is main
+        run: |
+          echo "Github ref: $GITHUB_REF"
+          GIT_BRANCH=${{ env.BRANCH_NAME }}
+          echo "Current branch is $GIT_BRANCH"
+          if [ "$GIT_BRANCH" != "main" ]; then
+              echo 'Aborting workflow -- not running on main'
+              exit 1 # need some way to kill whole workflow, not just step
+          fi
+          echo "Current branch is main, proceeding with release process"
+
   version:
     runs-on: ubuntu-latest
+    needs:
+      - check-branch
     env:
       RELEASE_TAG: "${{ github.event.release.tag_name}}"
     outputs:
